"""empty message

Revision ID: b8a391e61706
Revises: 8c47b762a8cb
Create Date: 2020-06-27 13:45:15.309817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8a391e61706'
down_revision = '8c47b762a8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('mobile', sa.String(length=11), nullable=False))
    op.drop_index('phone_num', table_name='ih_user_profile')
    op.create_unique_constraint(None, 'ih_user_profile', ['mobile'])
    op.drop_column('ih_user_profile', 'password')
    op.drop_column('ih_user_profile', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('phone_num', mysql.VARCHAR(length=11), nullable=False))
    op.add_column('ih_user_profile', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    op.create_index('phone_num', 'ih_user_profile', ['phone_num'], unique=True)
    op.drop_column('ih_user_profile', 'mobile')
    # ### end Alembic commands ###
